spring.application.name=gestor-gastos
spring.datasource.url=jdbc:mysql://localhost:3306/gestor_gastos
spring.datasource.username=root
spring.datasource.password=johan2008

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true